an:
  frontpage: 89
  help docs: 9
  main: 92
ar:
  frontpage: 89
  help docs: 8
  main: 51
be-BY:
  frontpage: 100
  help docs: 11
  main: 95
bg-BG:
  frontpage: 15
  help docs: 2
  main: 43
ca:
  frontpage: 84
  help docs: 8
  main: 77
cmn:
  frontpage: 2
  help docs: 2
  main: 30
cs:
  frontpage: 89
  help docs: 8
  main: 78
da:
  frontpage: 89
  help docs: 9
  main: 92
de:
  frontpage: 100
  help docs: 40
  main: 100
el:
  frontpage: 100
  help docs: 47
  main: 100
eo:
  frontpage: 89
  help docs: 9
  main: 90
es:
  frontpage: 100
  help docs: 11
  main: 100
fa-IR:
  frontpage: 89
  help docs: 1
  main: 14
fi:
  frontpage: 0
  help docs: 0
  main: 7
fr:
  frontpage: 100
  help docs: 11
  main: 98
ga-IE:
  frontpage: 43
  help docs: 4
  main: 45
gl:
  frontpage: 48
  help docs: 9
  main: 71
he:
  frontpage: 92
  help docs: 8
  main: 66
hr:
  frontpage: 97
  help docs: 8
  main: 47
hu:
  frontpage: 100
  help docs: 66
  main: 100
id:
  frontpage: 48
  help docs: 3
  main: 55
it:
  frontpage: 89
  help docs: 9
  main: 92
it-CH:
  frontpage: 0
  help docs: 0
  main: 0
ja:
  frontpage: 61
  help docs: 5
  main: 65
km:
  frontpage: 12
  help docs: 2
  main: 51
ko:
  frontpage: 89
  help docs: 3
  main: 59
lv:
  frontpage: 0
  help docs: 0
  main: 0
mi:
  frontpage: 2
  help docs: 0
  main: 4
mk:
  frontpage: 89
  help docs: 4
  main: 56
ml:
  frontpage: 15
  help docs: 3
  main: 53
nl-NL:
  frontpage: 100
  help docs: 11
  main: 96
pl:
  frontpage: 89
  help docs: 1
  main: 18
pt-BR:
  frontpage: 100
  help docs: 63
  main: 100
pt-PT:
  frontpage: 28
  help docs: 0
  main: 10
ro:
  frontpage: 89
  help docs: 9
  main: 92
ru:
  frontpage: 100
  help docs: 8
  main: 65
sk:
  frontpage: 89
  help docs: 9
  main: 92
sl:
  frontpage: 100
  help docs: 11
  main: 95
sr:
  frontpage: 100
  help docs: 11
  main: 98
sr-RS:
  frontpage: 100
  help docs: 11
  main: 98
sv:
  frontpage: 89
  help docs: 9
  main: 91
te:
  frontpage: 25
  help docs: 2
  main: 29
tr:
  frontpage: 89
  help docs: 9
  main: 92
uk:
  frontpage: 100
  help docs: 8
  main: 79
ur:
  frontpage: 0
  help docs: 0
  main: 0
ur-PK:
  frontpage: 0
  help docs: 0
  main: 0
vi:
  frontpage: 12
  help docs: 3
  main: 46
zh-TW:
  frontpage: 100
  help docs: 9
  main: 93
