an:
  frontpage: 89
  main: 91
ar:
  frontpage: 89
  main: 48
be-BY:
  frontpage: 100
  main: 95
bg-BG:
  frontpage: 15
  main: 40
ca:
  frontpage: 84
  main: 76
cmn:
  frontpage: 0
  main: 29
cs:
  frontpage: 89
  main: 77
da:
  frontpage: 89
  main: 90
de:
  frontpage: 100
  main: 100
el:
  frontpage: 100
  main: 100
eo:
  frontpage: 89
  main: 89
es:
  frontpage: 100
  main: 100
fa-IR:
  frontpage: 89
  main: 12
fi:
  frontpage: 0
  main: 6
fr:
  frontpage: 100
  main: 98
ga-IE:
  frontpage: 35
  main: 43
gl:
  frontpage: 48
  main: 69
he:
  frontpage: 92
  main: 65
hr:
  frontpage: 97
  main: 46
hu:
  frontpage: 100
  main: 98
id:
  frontpage: 48
  main: 53
it:
  frontpage: 89
  main: 91
it-CH:
  frontpage: 0
  main: 0
ja:
  frontpage: 61
  main: 63
km:
  frontpage: 0
  main: 49
ko:
  frontpage: 89
  main: 57
lv:
  frontpage: 0
  main: 0
mi:
  frontpage: 2
  main: 3
mk:
  frontpage: 89
  main: 54
ml:
  frontpage: 0
  main: 51
nl-NL:
  frontpage: 100
  main: 96
pl:
  frontpage: 89
  main: 17
pt-BR:
  frontpage: 100
  main: 100
pt-PT:
  frontpage: 28
  main: 9
ro:
  frontpage: 89
  main: 91
ru:
  frontpage: 100
  main: 63
sk:
  frontpage: 89
  main: 91
sl:
  frontpage: 100
  main: 95
sr:
  frontpage: 100
  main: 98
sr-RS:
  frontpage: 100
  main: 98
sv:
  frontpage: 89
  main: 90
te:
  frontpage: 20
  main: 26
tr:
  frontpage: 89
  main: 91
uk:
  frontpage: 100
  main: 77
ur:
  frontpage: 0
  main: 0
ur-PK:
  frontpage: 0
  main: 0
vi:
  frontpage: 0
  main: 43
zh-TW:
  frontpage: 100
  main: 93
